server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: nunsub-backend
  profiles:
    active: credentials
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true