spring:
  datasource:
    url: ${POST_DB_URL}
    username: ${POST_DB_USERNAME}
    password: ${POST_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  secondary-auth-token-expiration: ${JWT_SECONDARY_AUTH_TOKEN_EXPIRATION}

openbanking:
  # authorize-url: https://testapi.openbanking.or.kr/oauth/2.0/authorize
  # token-url: https://testapi.openbanking.or.kr/oauth/2.0/token
  # base-url: https://testapi.openbanking.or.kr/
  authorize-url: http://localhost:8080/mock/openbanking/oauth/2.0/authorize # Mock URL
  token-url: http://localhost:8080/mock/openbanking/oauth/2.0/token # Mock URL
  base-url: http://localhost:8080/mock/openbanking # Mock URL
  client-id: ${OPENBANKING_CLIENT_ID}
  client-secret: ${OPENBANKING_CLIENT_SECRET}
  client-use-code: 1234567890a
  redirect-uri: ${OPENBANKING_REDIRECT_URI}
  scope: login%20inquiry%20transfer
  mtls:
    cert-path: "classpath:certs/openbanking_test_client.p12"
    cert-password: "test_password"
  crypto:
    secret-key: {OPENBANKING_CRYPTO_SECRET_KEY}