name: Deploy to GCE with Blue-Green (nunsub)

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-west1
  SERVICE_NAME: nunsub-backend

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit --region=${{ env.GAR_LOCATION }} \
          --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:latest

  deploy:
    name: Deploy to GCE with Blue-Green Deployment
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to GCE
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            export IMAGE_TAG=${{ github.sha }}
            
            cd /home/ehgns79513/nunsub
            
            # Here Document을 사용하여 .env 파일을 한 번에, 더 안전하게 생성합니다.
            cat <<EOF > .env
            POST_DB_URL=${{ secrets.POST_DB_URL }}
            POST_DB_USERNAME=${{ secrets.POST_DB_USERNAME }}
            POST_DB_PASSWORD=${{ secrets.POST_DB_PASSWORD }}
            DDL_AUTO=${{ secrets.DDL_AUTO }}
            SHOW_SQL=${{ secrets.SHOW_SQL }}
            MONGO_DB_URl=${{ secrets.MONGO_DB_URl }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}
            JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
            JWT_SECONDARY_AUTH_TOKEN_EXPIRATION=${{ secrets.JWT_SECONDARY_AUTH_TOKEN_EXPIRATION }}
            OPENBANKING_CLIENT_ID=${{ secrets.OPENBANKING_CLIENT_ID }}
            OPENBANKING_CLIENT_SECRET=${{ secrets.OPENBANKING_CLIENT_SECRET }}
            OPENBANKING_REDIRECT_URI=${{ secrets.OPENBANKING_REDIRECT_URI }}
            OPENBANKING_CRYPTO_SECRET_KEY=${{ secrets.OPENBANKING_CRYPTO_SECRET_KEY }}
            EOF

            
            # Docker 인증 및 배포 스크립트 실행
            gcloud auth configure-docker us-west1-docker.pkg.dev
            ./deploy.sh